# Generated by Django 3.0.5 on 2020-04-20 02:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agmminutes',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='committeeminutes',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
