# Generated by Django 3.0.5 on 2020-04-05 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventComps',
            new_name='EventComp',
        ),
    ]
