# Generated by Django 3.0.5 on 2021-03-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_delete_eventmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcomp',
            name='event_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
