# Generated by Django 3.0.5 on 2021-09-21 13:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20210921_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventintro',
            name='event_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
