# Generated by Django 3.0.5 on 2021-09-22 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventintro_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventintro',
            name='event_id',
        ),
    ]
