# Generated by Django 3.0.5 on 2020-06-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('A', 'Apparel'), ('O', 'Other'), ('E', 'Equipment')], default='A', max_length=2),
            preserve_default=False,
        ),
    ]
