# Generated by Django 3.0.5 on 2020-04-27 04:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/albums/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='photos/albums/thumbnails')),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('date_published', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('feature_image', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='feature', to='gallery.Image')),
                ('images', models.ManyToManyField(blank=True, related_name='images', to='gallery.Image')),
            ],
        ),
    ]
