# Generated by Django 3.0.5 on 2020-04-29 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200427_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='feature_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature', to='gallery.Image'),
        ),
    ]
