# Generated by Django 3.0.5 on 2020-04-09 01:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_delete_eventmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactIntro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('left_right', models.CharField(max_length=10)),
                ('shot_before', models.CharField(max_length=50)),
                ('shot_before_desc', models.CharField(max_length=250)),
                ('reason', models.CharField(max_length=15)),
                ('contact_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('event_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.EventIntro')),
            ],
        ),
    ]
