# Generated by Django 3.0.5 on 2020-04-09 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactintro',
            name='shot_before_desc',
        ),
    ]
