# Generated by Django 3.0.5 on 2020-07-01 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_delete_eventmaster'),
        ('contact_forms', '0002_remove_contactintro_shot_before_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactintro',
            name='event_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.EventIntro'),
        ),
    ]
