# Generated by Django 3.0.5 on 2021-09-21 13:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contact_forms', '0003_auto_20200702_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactintro',
            name='contact_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
