# Generated by Django 3.0.5 on 2020-06-25 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagecontent',
            old_name='description',
            new_name='content',
        ),
    ]
