# Generated by Django 3.0.5 on 2020-06-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200625_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
