# Generated by Django 3.0.5 on 2020-06-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200625_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='name',
            field=models.CharField(default='archery', max_length=100),
            preserve_default=False,
        ),
    ]
