# Generated by Django 3.0.5 on 2020-06-26 11:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_pagecontent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
