# Generated by Django 3.0.5 on 2020-04-22 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('archery_australia_id', models.IntegerField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='photos/users')),
                ('member_expiry', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LifeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('year_made', models.IntegerField(blank=True)),
                ('date_active_start', models.IntegerField(blank=True)),
                ('date_active_end', models.IntegerField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='photos/users')),
                ('short_desc', models.CharField(blank=True, max_length=250)),
                ('long_desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('position', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('short_desc', models.CharField(blank=True, max_length=250)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
