# Generated by Django 3.0.5 on 2020-04-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='archer_class',
            field=models.CharField(choices=[('Cub', 'Cub'), ('Intermediate', 'Intermediate'), ('Cadet', 'Cadet'), ('20 & Under', '20 & Under'), ('Open', 'Open'), ('Master', 'Master'), ('Veteran', 'Veteran'), ('Veteran+', 'Veteran+'), ('Para Archer', 'Para Archer'), ('Vision Impaired', 'Vision Impaired')], default='Open', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='division',
            field=models.CharField(choices=[('Recurve', 'Recurve'), ('Compound', 'Compound'), ('Longbow', 'Longbow'), ('Barebow Recurve', 'Barebow Recurve'), ('Barebow Compound', 'Barebow Compound'), ('Crossbow', 'Crossbow')], default='Recurve', max_length=20),
        ),
    ]
