# Generated by Django 3.0.5 on 2020-04-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200424_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, default='photos/users/user_placeholder.jpg', upload_to='photos/users'),
        ),
    ]
