# Generated by Django 3.0.5 on 2020-07-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200425_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='order',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
