# Generated by Django 3.0.5 on 2020-07-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_committee_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
