# Generated by Django 3.0.5 on 2021-09-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200714_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/users'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='member',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
