# Generated by Django 3.0.5 on 2021-09-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210921_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='photo',
            field=models.ImageField(default='/user_placeholder.jpg', upload_to='photos/users'),
        ),
    ]
