# Generated by Django 3.0.5 on 2021-09-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_committee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='photo',
            field=models.ImageField(default='photos/users/user_placeholder.jpg', upload_to='photos/users'),
        ),
    ]
