# Generated by Django 3.0.5 on 2020-04-04 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('short_title', models.CharField(max_length=50)),
                ('announcement', models.TextField()),
                ('short_announcement', models.CharField(max_length=140)),
                ('is_published', models.BooleanField(default=True)),
                ('date_published', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
