# Generated by Django 3.0.5 on 2020-04-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='short_announcement',
            field=models.CharField(max_length=250),
        ),
    ]
