# Generated by Django 3.0.5 on 2020-07-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_auto_20200405_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='members_only',
            field=models.BooleanField(default=True),
        ),
    ]
