# Generated by Django 3.0.5 on 2021-09-22 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_announcement_members_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='members_only',
        ),
    ]
