# Generated by Django 3.0.5 on 2021-10-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_remove_announcement_members_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='short_title',
            field=models.CharField(default='Short Title', max_length=50),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='Title', max_length=140),
        ),
    ]
