# Generated by Django 3.0.5 on 2020-06-25 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageContent',
        ),
    ]
