"""
Django settings for geelong_archers project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

from django.contrib.messages import constants as messages
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&gsosw7gw7m9i!q%dx-+aq@6q$&2vkp62tzj8z-j7+q%c3fr=r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.0.4', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django_template_maths',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts.apps.AccountsConfig',
    'announcements.apps.AnnouncementsConfig',
    'awards.apps.AwardsConfig',
    'contact_forms.apps.ContactFormsConfig',
    'custom_admin.apps.CustomAdminConfig',
    'events.apps.EventsConfig',
    'gallery.apps.GalleryConfig',
    'minutes.apps.MinutesConfig',
    'pages.apps.PagesConfig',
    'rankings.apps.RankingsConfig',
    'store.apps.StoreConfig',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'geelong_archers.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],

        },
    },
]


WSGI_APPLICATION = 'geelong_archers.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'geelong_archers',
        'USER': 'postgres',
        'PASSWORD': 's1bc9kAV',
        'HOST': 'localhost'
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Australia/Melbourne'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'geelong_archers/static')
]

# Media Folder Settings
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Messages
MESSAGE_TAGS = {
    messages.ERROR: 'danger'
}

# Custom User Model
AUTH_USER_MODEL = 'accounts.Account'

# Clickjacking protection changed from deny to allowed iframe from same origin
X_FRAME_OPTIONS = 'SAMEORIGIN'


STRIPE_PUBLIC_KEY = 'pk_test_51H0dbuEzN3Vgf8p6nRQ3QMdT9ZdcmLTtfCqbcey0krLRKAScHDbE7Qtdc8HkRUrb9tmTvZnDyGr1yWhcq0rl1Ezy00c0q5EQHo'
STRIPE_SECRET_KEY = 'sk_test_51H0dbuEzN3Vgf8p63Be79PRYMMQ0l5k60Zg1AX0zsEo4drQ52JJEJgrANaLKWHNgGU3ae1p0UxUotZ4TUy4ZZGGY00qHncpF3b'

try:
    from .local_settings import *
except ImportError:
    pass
