# Generated by Django 3.0.5 on 2020-04-22 06:27

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.ImageField(blank=True, upload_to='awards/')),
            ],
        ),
        migrations.CreateModel(
            name='MemberEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('event_name', models.CharField(max_length=100)),
                ('club', models.CharField(max_length=100)),
                ('discipline', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('day', models.IntegerField()),
                ('flight', models.IntegerField()),
                ('archer_class', models.CharField(max_length=20)),
                ('division', models.CharField(max_length=20)),
                ('archery_round', models.CharField(max_length=40)),
                ('score', models.IntegerField()),
                ('rating', models.FloatField()),
                ('awards', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), size=None), size=None)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberAwards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recieved', models.DateField()),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='awards.Awards')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
