# Generated by Django 3.0.5 on 2020-04-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_memberavailableawards'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberevents',
            name='total_awards',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
