# Generated by Django 3.0.5 on 2020-04-23 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0005_auto_20200423_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberclassification',
            name='classification_id',
            field=models.ForeignKey(default='1200', on_delete=django.db.models.deletion.PROTECT, to='awards.Awards'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberclassificationannual',
            name='classification_id',
            field=models.ForeignKey(default=1200, on_delete=django.db.models.deletion.PROTECT, to='awards.Awards'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='awards',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
